// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SongInput struct {
	Name string  `json:"name"`
	URL  *string `json:"url,omitempty"`
	Tone *string `json:"tone,omitempty"`
}
